-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

unfoldr f (x:y:t) = x : (unfoldr f (y : (f x y) : t))
fibonaccis = unfoldr (+) [0, 1]

solution = sum $ takeWhile (<4000000) [x | x <- fibonaccis, even x]
